apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandacloud-app
  labels:
    app: pandacloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pandacloud-app
  template:
    metadata:
      labels:
        app: pandacloud-app
    spec:
      containers:
      - name: pandacloud-container
        image: ramkumarhub/amazon-clone
        ports:
        - containerPort: 3000
